version: '2.1'

services:
  syslog-echo:
    image: syslog-echo
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 514:514
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js